"""Create hotels tables with id column

Revision ID: 55823d149571
Revises: 
Create Date: 2024-10-29 11:03:11.406473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55823d149571'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotels')
    # ### end Alembic commands ###
